### ISSUE TITLE
error Invalid regular expression

### ISSUE THREAD

**Issue by 2mori** [iamport/iamport-react-native#120]
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
debug SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (D:\React-native\iamport-react-native\example\node_modules\metro-config\src\defaults\blacklist.js:34:10)   
    at getBlacklistRE (D:\React-native\iamport-react-native\example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:61:59)
    at getDefaultConfig (D:\React-native\iamport-react-native\example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:75:20)
    at load (D:\React-native\iamport-react-native\example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:103:25)
    at Object.runServer [as func] (D:\React-native\iamport-react-native\example\node_modules\@react-native-community\cli\build\commands\server\runServer.js:72:58)
    at D:\React-native\iamport-react-native\example\node_modules\@react-native-community\cli\build\cliEntry.js:152:22  

클론해서
npm install
npm start -- --reset-cache   

윈도우 10 환경입니다.

후 위와 같은 에러가 발생합니다. 어떻게 해결해야하나요?

**Comment by 2mori** [comment]
https://hongku.tistory.com/400 보고 해당문제는 해결했습니다.
